name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

# Add these lines to force write permissions for this file
permissions:
  contents: write

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push empty commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Keep-alive ping to reset Streamlit idle timer"
          git push
